// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rigger/protos.proto

package rigger

import (
	bytes "bytes"
	fmt "fmt"
	actor "github.com/AsynkronIT/protoactor-go/actor"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 用于远程启动子进程的命令
type RemoteStartChildCmd struct {
	SpecOrArgs []byte `protobuf:"bytes,1,opt,name=specOrArgs,proto3" json:"specOrArgs,omitempty"`
}

func (m *RemoteStartChildCmd) Reset()      { *m = RemoteStartChildCmd{} }
func (*RemoteStartChildCmd) ProtoMessage() {}
func (*RemoteStartChildCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a1f10097eb08ff, []int{0}
}
func (m *RemoteStartChildCmd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoteStartChildCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoteStartChildCmd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoteStartChildCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteStartChildCmd.Merge(m, src)
}
func (m *RemoteStartChildCmd) XXX_Size() int {
	return m.Size()
}
func (m *RemoteStartChildCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteStartChildCmd.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteStartChildCmd proto.InternalMessageInfo

func (m *RemoteStartChildCmd) GetSpecOrArgs() []byte {
	if m != nil {
		return m.SpecOrArgs
	}
	return nil
}

// 表示成功的回复
type OkResp struct {
}

func (m *OkResp) Reset()      { *m = OkResp{} }
func (*OkResp) ProtoMessage() {}
func (*OkResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a1f10097eb08ff, []int{1}
}
func (m *OkResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OkResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OkResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OkResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OkResp.Merge(m, src)
}
func (m *OkResp) XXX_Size() int {
	return m.Size()
}
func (m *OkResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OkResp.DiscardUnknown(m)
}

var xxx_messageInfo_OkResp proto.InternalMessageInfo

// 表示出错的回复
type ErrorResp struct {
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *ErrorResp) Reset()      { *m = ErrorResp{} }
func (*ErrorResp) ProtoMessage() {}
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a1f10097eb08ff, []int{2}
}
func (m *ErrorResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrorResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResp.Merge(m, src)
}
func (m *ErrorResp) XXX_Size() int {
	return m.Size()
}
func (m *ErrorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResp proto.InternalMessageInfo

func (m *ErrorResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// 起进程回复
type SpawnResponse struct {
	Sender *actor.PID `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Parent *actor.PID `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Pid    *actor.PID `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Error  string     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SpawnResponse) Reset()      { *m = SpawnResponse{} }
func (*SpawnResponse) ProtoMessage() {}
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5a1f10097eb08ff, []int{3}
}
func (m *SpawnResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpawnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpawnResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpawnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnResponse.Merge(m, src)
}
func (m *SpawnResponse) XXX_Size() int {
	return m.Size()
}
func (m *SpawnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnResponse proto.InternalMessageInfo

func (m *SpawnResponse) GetSender() *actor.PID {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *SpawnResponse) GetParent() *actor.PID {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *SpawnResponse) GetPid() *actor.PID {
	if m != nil {
		return m.Pid
	}
	return nil
}

func (m *SpawnResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RemoteStartChildCmd)(nil), "rigger.RemoteStartChildCmd")
	proto.RegisterType((*OkResp)(nil), "rigger.OkResp")
	proto.RegisterType((*ErrorResp)(nil), "rigger.ErrorResp")
	proto.RegisterType((*SpawnResponse)(nil), "rigger.SpawnResponse")
}

func init() { proto.RegisterFile("rigger/protos.proto", fileDescriptor_f5a1f10097eb08ff) }

var fileDescriptor_f5a1f10097eb08ff = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xed, 0xaf, 0x1f, 0x11, 0x35, 0xb0, 0xa4, 0x0c, 0x11, 0x42, 0x57, 0x90, 0x89, 0x85,
	0x44, 0xe2, 0xdf, 0x5e, 0x0a, 0x43, 0xa7, 0xa2, 0x94, 0x17, 0x48, 0x13, 0x2b, 0x8d, 0x4a, 0x6c,
	0xeb, 0xda, 0x08, 0xb1, 0xb1, 0xb3, 0xf0, 0x18, 0x3c, 0x0a, 0x63, 0xc6, 0x8e, 0xc4, 0x59, 0x18,
	0xfb, 0x08, 0x28, 0x09, 0x12, 0x45, 0x9d, 0xec, 0x73, 0xce, 0xef, 0x48, 0x47, 0x97, 0x0d, 0x30,
	0xcf, 0x32, 0x8e, 0xa1, 0x42, 0x69, 0xa4, 0x0e, 0xda, 0xc7, 0x75, 0x3a, 0xf3, 0xe0, 0x2a, 0xcb,
	0xcd, 0xfc, 0x71, 0x16, 0x24, 0xb2, 0x08, 0x87, 0xfa, 0x59, 0x2c, 0x50, 0x8a, 0xf1, 0x7d, 0xc7,
	0xc6, 0x89, 0x91, 0x78, 0x9a, 0xc9, 0xb0, 0xfd, 0xfc, 0xe9, 0xfb, 0x97, 0x6c, 0x10, 0xf1, 0x42,
	0x1a, 0x3e, 0x35, 0x31, 0x9a, 0xd1, 0x3c, 0x7f, 0x48, 0x47, 0x45, 0xea, 0x02, 0x63, 0x5a, 0xf1,
	0x64, 0x82, 0x43, 0xcc, 0xb4, 0x47, 0x8f, 0xe8, 0xc9, 0x6e, 0xb4, 0xe6, 0xf8, 0xdb, 0xcc, 0x99,
	0x2c, 0x22, 0xae, 0x95, 0x7f, 0xcc, 0xfa, 0xb7, 0x88, 0x12, 0x1b, 0xe1, 0xee, 0xb3, 0x2d, 0xde,
	0x88, 0xb6, 0xd1, 0x8f, 0x3a, 0xe1, 0xbf, 0x52, 0xb6, 0x37, 0x55, 0xf1, 0x93, 0x68, 0x18, 0x29,
	0x34, 0x77, 0x7d, 0xe6, 0x68, 0x2e, 0x52, 0xde, 0x81, 0x3b, 0x67, 0x2c, 0x68, 0xa7, 0x05, 0x77,
	0xe3, 0x9b, 0xe8, 0x27, 0x69, 0x18, 0x15, 0x23, 0x17, 0xc6, 0xfb, 0xb7, 0xc9, 0x74, 0x89, 0x7b,
	0xc8, 0x7a, 0x2a, 0x4f, 0xbd, 0xde, 0x06, 0xd0, 0xd8, 0xbf, 0x6b, 0xfe, 0xaf, 0xad, 0xb9, 0xbe,
	0x28, 0x2b, 0x20, 0xcb, 0x0a, 0xc8, 0xaa, 0x02, 0xfa, 0x62, 0x81, 0xbe, 0x5b, 0xa0, 0x1f, 0x16,
	0x68, 0x69, 0x81, 0x7e, 0x5a, 0xa0, 0x5f, 0x16, 0xc8, 0xca, 0x02, 0x7d, 0xab, 0x81, 0x94, 0x35,
	0x90, 0x65, 0x0d, 0x64, 0xe6, 0xb4, 0xe7, 0x3a, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x4c,
	0x66, 0x2c, 0x85, 0x01, 0x00, 0x00,
}

func (this *RemoteStartChildCmd) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RemoteStartChildCmd)
	if !ok {
		that2, ok := that.(RemoteStartChildCmd)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.SpecOrArgs, that1.SpecOrArgs) {
		return false
	}
	return true
}
func (this *OkResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OkResp)
	if !ok {
		that2, ok := that.(OkResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *ErrorResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ErrorResp)
	if !ok {
		that2, ok := that.(ErrorResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *SpawnResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SpawnResponse)
	if !ok {
		that2, ok := that.(SpawnResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Sender.Equal(that1.Sender) {
		return false
	}
	if !this.Parent.Equal(that1.Parent) {
		return false
	}
	if !this.Pid.Equal(that1.Pid) {
		return false
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *RemoteStartChildCmd) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rigger.RemoteStartChildCmd{")
	s = append(s, "SpecOrArgs: "+fmt.Sprintf("%#v", this.SpecOrArgs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OkResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&rigger.OkResp{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ErrorResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rigger.ErrorResp{")
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SpawnResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&rigger.SpawnResponse{")
	if this.Sender != nil {
		s = append(s, "Sender: "+fmt.Sprintf("%#v", this.Sender)+",\n")
	}
	if this.Parent != nil {
		s = append(s, "Parent: "+fmt.Sprintf("%#v", this.Parent)+",\n")
	}
	if this.Pid != nil {
		s = append(s, "Pid: "+fmt.Sprintf("%#v", this.Pid)+",\n")
	}
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringProtos(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *RemoteStartChildCmd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoteStartChildCmd) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.SpecOrArgs) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProtos(dAtA, i, uint64(len(m.SpecOrArgs)))
		i += copy(dAtA[i:], m.SpecOrArgs)
	}
	return i, nil
}

func (m *OkResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OkResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *ErrorResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrorResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProtos(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func (m *SpawnResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpawnResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Sender != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProtos(dAtA, i, uint64(m.Sender.Size()))
		n1, err := m.Sender.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Parent != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintProtos(dAtA, i, uint64(m.Parent.Size()))
		n2, err := m.Parent.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Pid != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProtos(dAtA, i, uint64(m.Pid.Size()))
		n3, err := m.Pid.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Error) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintProtos(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func encodeVarintProtos(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RemoteStartChildCmd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SpecOrArgs)
	if l > 0 {
		n += 1 + l + sovProtos(uint64(l))
	}
	return n
}

func (m *OkResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ErrorResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovProtos(uint64(l))
	}
	return n
}

func (m *SpawnResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sender != nil {
		l = m.Sender.Size()
		n += 1 + l + sovProtos(uint64(l))
	}
	if m.Parent != nil {
		l = m.Parent.Size()
		n += 1 + l + sovProtos(uint64(l))
	}
	if m.Pid != nil {
		l = m.Pid.Size()
		n += 1 + l + sovProtos(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovProtos(uint64(l))
	}
	return n
}

func sovProtos(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProtos(x uint64) (n int) {
	return sovProtos(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *RemoteStartChildCmd) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RemoteStartChildCmd{`,
		`SpecOrArgs:` + fmt.Sprintf("%v", this.SpecOrArgs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OkResp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OkResp{`,
		`}`,
	}, "")
	return s
}
func (this *ErrorResp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ErrorResp{`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SpawnResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SpawnResponse{`,
		`Sender:` + strings.Replace(fmt.Sprintf("%v", this.Sender), "PID", "actor.PID", 1) + `,`,
		`Parent:` + strings.Replace(fmt.Sprintf("%v", this.Parent), "PID", "actor.PID", 1) + `,`,
		`Pid:` + strings.Replace(fmt.Sprintf("%v", this.Pid), "PID", "actor.PID", 1) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringProtos(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *RemoteStartChildCmd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtos
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoteStartChildCmd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoteStartChildCmd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecOrArgs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecOrArgs = append(m.SpecOrArgs[:0], dAtA[iNdEx:postIndex]...)
			if m.SpecOrArgs == nil {
				m.SpecOrArgs = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtos(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OkResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtos
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OkResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OkResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProtos(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErrorResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtos
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrorResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrorResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtos(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpawnResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtos
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpawnResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpawnResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sender == nil {
				m.Sender = &actor.PID{}
			}
			if err := m.Sender.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Parent == nil {
				m.Parent = &actor.PID{}
			}
			if err := m.Parent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pid == nil {
				m.Pid = &actor.PID{}
			}
			if err := m.Pid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProtos
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProtos
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtos(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProtos
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProtos(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProtos
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtos
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProtos
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthProtos
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProtos
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProtos(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthProtos
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProtos = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProtos   = fmt.Errorf("proto: integer overflow")
)
